services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: bb-platform-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_URL=sqlite:////app/bugbounty.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=false
    depends_on:
      - redis
    networks:
      - bb-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: bb-platform-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - bb-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: bb-platform-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bb-network
    restart: unless-stopped

  # Celery Worker (for background tasks)
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: bb-platform-celery-worker
    command: celery -A app.core.celery.celery_app worker --loglevel=info
    volumes:
      - backend_data:/app
    environment:
      - DATABASE_URL=sqlite:////app/bugbounty.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      - redis
      - backend
    networks:
      - bb-network
    restart: unless-stopped

  # Celery Beat (for scheduled tasks)
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: bb-platform-celery-beat
    command: celery -A app.core.celery.celery_app beat --loglevel=info
    volumes:
      - backend_data:/app
    environment:
      - DATABASE_URL=sqlite:////app/bugbounty.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      - redis
      - backend
    networks:
      - bb-network
    restart: unless-stopped

  # Flower (Celery monitoring)
  flower:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: bb-platform-flower
    command: celery -A app.core.celery.celery_app flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - backend_data:/app
    environment:
      - DATABASE_URL=sqlite:////app/bugbounty.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - celery-worker
    networks:
      - bb-network
    restart: unless-stopped

volumes:
  backend_data:
  redis_data:

networks:
  bb-network:
    driver: bridge 